on:
  release:
    types: [created]

name: Create Release

jobs:
  deploy:
    name: Deploy to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install publishing requirements
        run: pip install twine

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.pypi_username }} -p ${{ secrets.pypi_password }}
