on:
  push:
    branches:
      - "releases/**"

name: Release and deploy

jobs:
  deploy:
    name: Deploy to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Build code
        run: python setup.py sdist

      - name: Install publishing requirements
        run: pip install twine

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.pypi_username }} -p ${{ secrets.pypi_password }}

  create_release:
    needs: deploy
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Automatical release ${{ github.ref }}
          draft: false
          prerelease: false
